app:
    name: BoblightPi
    description: Java implementation of the boblight server with enhanced functionality. The target plattform is the RaspiPi.

boblight:
    port: 19333
    protocolVersion: 5
    config: config/boblight.conf
    lightOffset: -1
    maxBlocks: 80


