app:
    name: BoblightServer
    description: Java implementation of the boblight server with enhanced functionality.

boblight:
    port: 19333
    protocolVersion: 5
    config: config/boblight.conf
    lightOffset: -1
    maxBlocks: 40


